services:
  - type: web
    name: mindful-moments-ui
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip show streamlit
    startCommand: |
      echo "✅ Starting Streamlit UI..."
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
