services:
  - type: web
    name: mindful-moments-app
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m streamlit run app.py --server.port 10000 --server.address 0.0.0.0"
